### ISSUE TITLE
Incompatibility - Slot Cycler

### ISSUE THREAD

**Issue by AzuryxxVortex** [Crendgrim/AutoHUD#94] opened 2024-02-27 03:12 UTC
Well this is self explanatory-

Here's the mod page.
https://www.curseforge.com/minecraft/mc-mods/slot-cycler

Just throwing this out there-

**Comment by Crendgrim** [comment] 2024-02-27 09:45
Duplicate of #87

**Closed by Crendgrim** 2024-02-27 09:45 UTC
Labels: duplicate
