### ISSUE TITLE
Item Fade-out limit only works during animation.

### ISSUE THREAD

**Issue by unweeked** [Crendgrim/AutoHUD#122] opened 2024-07-16 07:01 UTC
When setting the item fade-out limit to a value other than 0, that limit is only used for the fade-out animation. After the animation is over, the items are not visible at all.
Forge 1.20.1 v6.3.5

**Comment by Crendgrim** [comment] 2024-07-17 12:10
Pushed a fix version for 1.20.1-forge and 1.21-neoforge. If anyone needs it for an inbetween version, let me know.

**Closed by Crendgrim** 2024-07-17 12:10 UTC
Labels: bug, forge

**Comment by Mirsario** [comment] 2024-07-30 12:35
This also occurs on Fabric under MC 1.20.1 & other. Please post a build of v6.3.6 for it, thank you.


https://github.com/user-attachments/assets/c4ff9059-01f1-4b02-9360-5961eee6493c

(Plus I'm not sure why the pickaxe and the cobblestone don't fade out at all, may be my mods)

**Comment by Crendgrim** [comment] 2024-07-30 13:05
I cannot replicate this on Fabric 1.20.1. I wonder if that other mod that causes pickaxe + cobblestone to not be fully faded out is the cause here. Are you using ImmediatelyFast? If so, you need to disable its HUD batching feature to use AutoHUD's fade.

**Comment by Crendgrim** [comment] 2024-07-30 15:41
Ah I see. True, that is confusing. I will put that on my list.
