### ISSUE TITLE
Doesn't seem to respect OneBar's "Hotbar item tooltip down" option

### ISSUE THREAD

**Issue by Madis0** [Crendgrim/AutoHUD#34] opened 2023-01-14 09:17 UTC
AutoHUD always seems to use the vanilla height for the hotbar tooltip, regardless of whether that option is enabled.

https://github.com/Madis0/OneBar/blob/main/src/main/java/io/github/madis0/mixin/InGameHudMixin.java#L78

**Comment by Crendgrim** [comment] 2023-02-15 15:35
I cannot reproduce this anymore with the latest AutoHUD and OneBar. Either it magically got fixed by me cleaning up, or you did something in the meantime. Hurray for it working fine now, though ;)

**Closed by Crendgrim** 2023-02-15 15:35 UTC
Labels: bug, mod-compatibility
