### ISSUE TITLE
Enabling the Fade effect misaligns hotbar items slightly

### ISSUE THREAD

**Issue by VindSole** [Crendgrim/AutoHUD#134] opened 2024-09-30 03:10 UTC
As title says, having the fade effect enabled causes items to be slightly off by a couple of pixels vertically.

I think this also causes an issue in the mod Raised, because items go exponentially off center when increasing the vertical axis in the hotbar.

Fade disabled
![image](https://github.com/user-attachments/assets/1c1bd64b-9db7-4c46-b5f2-e6a5e337efa0)

Fade enabled
![image](https://github.com/user-attachments/assets/a5f2cb35-a703-47d3-9696-232a46546dc7)

Vertical set to %23 in Raised settings, happens when fade effect is enabled.
![image](https://github.com/user-attachments/assets/f4e107aa-df88-4e5c-8e86-2eea62a09fe4)

Seems to be the only issue in Raised 4.0.0 and MC 1.21.1, so I suppose both mods are compatible?

**Comment by Crendgrim** [comment] 2024-09-30 09:23
Technically a duplicate of #125, but the fact that it only happens in "fade" mode is very interesting. Thank you!

**Closed** 2024-11-28 19:40 UTC
Labels: bug, mod-compatibility, fixed-in-next-version
